name: Test Project
on: push # TRIGGER - Keyword that controls when the workflow will run
jobs:
    test:
        runs-on: ubuntu-latest #The server is owned by Git-hub where the actions run
        steps:
          - name: Download Code #The code by default are not present in server which needs to be downloaded first
          # Action - An application that performs a frequently repeated task using command like run
            uses: actions/checkout@v4 #uses is used when we have to use Action
          - name: Install NodeJS
            uses: actions/setup-node@v4
            with:
                node-version: '18'
          - name: Install Dependencies
            run: npm ci
          - name: Run Tests
            run: npm test




